- README.md
> READMEに項目を追加

- package.json
- src/App.js
- src/components/FooterMenuButton.jsx
- src/components/HeaderMenu.jsx
- src/components/HeaderMenuButton.jsx
- src/styles.css
> headermenu編集

- package.json
- src/components/FooterMenuButton.jsx
- src/components/HeaderMenu.jsx
> header レスポンシブ作成

- src/App.js
- src/components/BaseLayout.jsx
- src/components/FooterMenu.jsx
- src/components/FooterMenuButton.jsx
- src/components/HeaderMenu.jsx
> FooterMenuに<p>

- src/components/FooterMenu.jsx
- src/components/FooterMenuButton.jsx
> footerスタイルの変更

- src/App.js
- src/components/BaseLayout.jsx
> baselayout

- src/components/FooterMenu.jsx
- src/components/FooterMenuButton.jsx
Reverts pythagoras-yamamoto/Osteopathic-Clinic#17
> Revert "配色と配置を修正"

- src/App.js
- src/components/HeaderMenu.jsx
> header nav

- src/components/FooterMenu.jsx
- src/components/FooterMenuButton.jsx
> フッターの配色と配置

- src/pages/HomePage.jsx
> Homepageの画像部分のデザイン追加

- src/components/HeaderMenu.jsx
> nav レイアウト右寄せに変更

- src/components/FooterMenu.jsx
- src/components/FooterMenuButton.jsx
> Footerほぼ終わり

- src/components/FooterMenu.jsx
> Footerのレスポンシブ

- package.json
- src/App.js
- src/router/Router.jsx
Reverts pythagoras-yamamoto/Osteopathic-Clinic#32
> Revert "Revert "router作成""

- src/components/HeaderMenu.jsx
- src/pages/AboutUsPage.jsx
- src/pages/InqueryPage.jsx
- src/pages/ResearvationPage.jsx
- src/router/Router.jsx
Reverts pythagoras-yamamoto/Osteopathic-Clinic#35
> Revert "router完成"

- src/components/HeaderMenu.jsx
- src/pages/AboutUsPage.jsx
- src/pages/InqueryPage.jsx
- src/pages/ResearvationPage.jsx
- src/router/Router.jsx
Reverts pythagoras-yamamoto/Osteopathic-Clinic#36
> Revert "Revert "router完成""

- src/components/FooterMenu.jsx
> foote リンク先指定

- src/components/FooterMenu.jsx
- src/components/HeaderMenu.jsx
Reverts pythagoras-yamamoto/Osteopathic-Clinic#39
> Revert "footerデザイン修正"

- src/components/FooterMenu.jsx
- src/components/HeaderMenu.jsx
Reverts pythagoras-yamamoto/Osteopathic-Clinic#40
> Revert "Revert "footerデザイン修正""

- public/index.html
> index head追加

- src/components/container/Access.jsx
- src/components/container/ContactContainer.jsx
- src/components/container/ContactForm.jsx
- src/components/container/ContainerA.jsx
- src/components/container/ContainerC.jsx
- src/components/container/LinkContactButton.jsx
- src/components/container/PriceTableContainer.jsx
- src/components/container/PriceTableElement.jsx
- src/components/footer/Footer.jsx
- src/components/header/Navbar.jsx
- src/pages/Home.jsx
- src/styles.css
サイトのフォントを全面的に変更した。Googleフォントに一新。
フォントにはLato、Kaisei Opti、Zen Kaku Gothic Antiqueを採用。
- デザインの崩れがないか
- 使用したフォントは適切か
- サイト全体としてバグは生じていないか
https://fonts.google.com/
https://meme-pro-git-pull-req-modify-font-style-pythagoras-yamamoto.vercel.app/
> フォントを全面的に変更

- src/components/footer/Footer.jsx
- src/components/header/NavSidebar.jsx
- src/components/header/Navbar.jsx
ブログのURLを変更したのでそれに伴いリンク先も新しいURLに一新
> ブログのURLを更新

- .github/workflows/main.yml
開発環境の整備を行いたい
github actionを利用してCI/CDを構築した
https://github.com/n05-frontend/shuwa-frontend-book-app/actions/runs/228739164
> GitHub Action Workflow 追加

- .github/dependabot.yml
> dependabotを追加

- package-lock.json
- package.json
- yarn.lock
Reverts pythagoras-yamamoto/osteopathic-clinic#131
> Revert "Bump @fullcalendar/timegrid from 5.11.0 to 5.11.3"

- package-lock.json
- package.json
- yarn.lock
Reverts pythagoras-yamamoto/osteopathic-clinic#125
> Revert "Bump @fullcalendar/google-calendar from 5.10.1 to 5.11.3"

- package-lock.json
- package.json
- yarn.lock
Reverts pythagoras-yamamoto/osteopathic-clinic#124
> Revert "Bump @fullcalendar/daygrid from 5.10.1 to 5.11.3"

- public/index.html
---
name: pull-request template
about: プルリク作成時のテンプレート
title: ''
labels: ''
assignees: ''
---
seo, ogp対策
> seo, ogp設定

- public/index.html
Reverts pythagoras-yamamoto/osteopathic-clinic#136
> Revert "seo, ogp設定"
